export const placesData = [
    { title: 'Noyo Coffee', description: 'Популярные блюда узбекской и европейской кухни Популярные блюда узбекской и европейской кухни Популярные блюда узбекской и европейской кухни', img: '/images/restaurants.webp', category: 'restaurants' },
    { title: 'Кафе Самарканд', description: 'Аутентичная узбекская кухня в историческом стиле', img: '../images/restaurants.webp', category: 'restaurants' },
    { title: 'Чайхана Бахор', description: 'Традиционный плов и лагман от местных поваров', img: '../images/restaurants.webp', category: 'restaurants' },
    { title: 'Музей Ремесел', description: 'Экспозиции народных промыслов и искусства', img: '/images/MUSEUMS.webp', category: 'museums' },
    { title: 'Гончарная мастерская', description: 'Живые демонстрации изготовления керамики', img: '../images/craft2.jpg', category: 'pottery' },
    { title: 'Дизайн-студия Oila', description: 'Смешение национального и современного стиля', img: '../images/craft4.jpg', category: 'designers' },
    { title: 'Сувенирная лавка', description: 'Эксклюзивные подарки и ручная работа', img: '../images/souvenirs.jpg', category: 'souvenirs' },
    { title: 'Ювелирная мастерская', description: 'Авторские украшения из серебра и камней', img: '../images/craft3\.jpg', category: 'craftsmen' },
    { title: 'Ткацкая галерея', description: 'Выставка традиционных узбекских тканей', img: '/images/tkani.webp', category: 'textile' },
    { title: 'Магазин керамики', description: 'Большой выбор расписной посуды и ваз', img: '../images/ceramics.jpg', category: 'ceramics' },
    { title: 'Галерея Современного Искусства', description: 'Инсталляции и выставки дизайнеров', img: '/images/MUSEUMS.webp', category: 'museums' },
    { title: 'Узбекский ресторан «Нон»', description: 'Домашняя кухня с живой музыкой', img: '../images/restaurants.webp', category: 'restaurants' },
    { title: 'Этно-дизайн центр', description: 'Декор и предметы интерьера ручной работы', img: '/images/decorations.webp', category: 'designers' },
    { title: 'Художественная студия', description: 'Картины, скульптуры и мастер-классы', img: '/images/art.jpg', category: 'craftsmen' },
    { title: 'Культурный павильон', description: 'Фольклорные представления и события', img: '/images/MUSEUMS.webp', category: 'museums' },
    { title: 'Мастерская игрушек', description: 'Авторские куклы и деревянные игрушки', img: '/images/toys.webp', category: 'craftsmen' },
    { title: 'Магазин тканей', description: 'Икат, адрас, хлопок — от местных производителей', img: '/images/tkani.webp', category: 'shops' },
    { title: 'Эко-лавка', description: 'Продукты и косметика местного производства', img: '/images/national_shop1.jpg', category: 'shops' },
];