export const placesData = [
    { title: 'Noyo Coffee', description: 'Популярные блюда узбекской и европейской кухни Популярные блюда узбекской и европейской кухни Популярные блюда узбекской и европейской кухни', img: '../images/craft3\.jpg', category: 'restaurants' },
    { title: 'Кафе Самарканд', description: 'Аутентичная узбекская кухня в историческом стиле', img: '../images/craft3\.jpg', category: 'restaurants' },
    { title: 'Чайхана Бахор', description: 'Традиционный плов и лагман от местных поваров', img: '../images/craft3\.jpg', category: 'restaurants' },
    { title: 'Музей Ремесел', description: 'Экспозиции народных промыслов и искусства', img: '../images/craft3\.jpg', category: 'museums' },
    { title: 'Гончарная мастерская', description: 'Живые демонстрации изготовления керамики', img: '../images/craft3\.jpg', category: 'pottery' },
    { title: 'Дизайн-студия Oila', description: 'Смешение национального и современного стиля', img: '../images/craft3\.jpg', category: 'designers' },
    { title: 'Сувенирная лавка', description: 'Эксклюзивные подарки и ручная работа', img: '../images/craft3\.jpg', category: 'souvenirs' },
    { title: 'Ювелирная мастерская', description: 'Авторские украшения из серебра и камней', img: '../images/craft3\.jpg', category: 'craftsmen' },
    { title: 'Ткацкая галерея', description: 'Выставка традиционных узбекских тканей', img: '../images/craft3\.jpg', category: 'textile' },
    { title: 'Магазин керамики', description: 'Большой выбор расписной посуды и ваз', img: '../images/craft3\.jpg', category: 'ceramics' },
    { title: 'Галерея Современного Искусства', description: 'Инсталляции и выставки дизайнеров', img: '../images/craft3\.jpg', category: 'museums' },
    { title: 'Узбекский ресторан «Нон»', description: 'Домашняя кухня с живой музыкой', img: '../images/craft3\.jpg', category: 'restaurants' },
    { title: 'Лавка сладостей', description: 'Национальные восточные сладости и чай', img: '../images/craft3\.jpg', category: 'shops' },
    { title: 'Этно-дизайн центр', description: 'Декор и предметы интерьера ручной работы', img: '../images/craft3\.jpg', category: 'designers' },
    { title: 'Художественная студия', description: 'Картины, скульптуры и мастер-классы', img: '../images/craft3\.jpg', category: 'craftsmen' },
    { title: 'Культурный павильон', description: 'Фольклорные представления и события', img: '../images/craft3\.jpg', category: 'museums' },
    { title: 'Мастерская игрушек', description: 'Авторские куклы и деревянные игрушки', img: '../images/craft3\.jpg', category: 'craftsmen' },
    { title: 'Магазин тканей', description: 'Икат, адрас, хлопок — от местных производителей', img: '../images/craft3\.jpg', category: 'shops' },
    { title: 'Чайный домик', description: 'Редкие сорта чая и атмосферные вечера', img: '../images/craft3\.jpg', category: 'restaurants' },
    { title: 'Эко-лавка', description: 'Продукты и косметика местного производства', img: '../images/craft3\.jpg', category: 'shops' },
];